language: python
os:
  - linux
  - osx
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
    - "python setup.py develop"
    - "pip install mirakuru[tests]"
    - "pip install coveralls"
    # rst files verifier, and pygments to parse code-blocks
    - "pip install restructuredtext_lint pygments"
    # code coverage tool
    - "pip install coveralls"
    # manually install wheel for deployment
    - "pip install wheel"
script:
    - "py.test --verbose --capture=no --showlocals --cov mirakuru"
    - "pylama"
    # pygments library used by rst-lint doesn't work on python 3.2.
    - "if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then for f in *.rst; do rst-lint $f; done; fi"
after_success:
    - coveralls
matrix:
    allow_failures:
        - os: osx
sudo: false

deploy:
    provider: pypi
    user: fizyk
    password:
        secure: IBVXG0zLKsBkzdeoC33Lxir01jbvDHdjQ81CPC8PbDPCmUozXgf9eqRFV5VOIYQOboTBzQYRq7RB8efeNKSH3nKf73iahwIYf4ezIxRzUaMzoY4GkyrC/0fQhMk1lAjexrRM1f2o7TIAALPUDyB/EaRcPCBEghxscQEeTlAw08c=
    on:
        tags: true
        all_branches: true
        repo: ClearcodeHQ/mirakuru
    distributions: "sdist bdist_wheel"
